name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn build
